"""
Service plugin for Hermes Agent — generated by Hermes Developer Agent.
Registers tools: service_list_services, service_get_service
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys

log = logging.getLogger(__name__)


# ── Tool schemas ──────────────────────────────────────────────────────────────

SERVICE_LIST_SERVICES_SCHEMA = {
    "type": "object",
    "properties": {},
    "required": [],
    "description": "List all services from Service. Returns a list of records.",
}

SERVICE_GET_SERVICE_SCHEMA = {
    "type": "object",
    "properties": {
        "record_id": {"type": "string", "description": "The ID of the service to retrieve."},
    },
    "required": ["record_id"],
    "description": "Get a single Service service by its ID.",
}

# ── Async → sync bridge (copy verbatim from any existing plugin) ──────────────

def _run(coro):
    """Run an async coroutine from a synchronous tool handler."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(asyncio.run, coro)
                return future.result()
        return loop.run_until_complete(coro)
    except RuntimeError:
        return asyncio.run(coro)


# ── Tool handlers ─────────────────────────────────────────────────────────────

def _service_list_services_handler(params: dict, **kwargs) -> str:
    try:
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        from agents.service_agent import list_services
        records = _run(list_services())
        log.info("service_list_services: returned %d records", len(records))
        return json.dumps({"records": records, "count": len(records)})
    except Exception as e:
        log.error("service_list_services error: %s", e)
        return json.dumps({"error": str(e)})

def _service_get_service_handler(params: dict, **kwargs) -> str:
    try:
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        from agents.service_agent import get_service
        record_id = params.get("record_id", "").strip()
        if not record_id:
            return json.dumps({"error": "record_id is required"})
        record = _run(get_service(record_id))
        if record is None:
            return json.dumps({"error": f"service {record_id} not found"})
        return json.dumps(record)
    except Exception as e:
        log.error("service_get_service error: %s", e)
        return json.dumps({"error": str(e)})

# ── Plugin entry point ────────────────────────────────────────────────────────

def setup(context) -> None:
    """Called by Hermes Agent plugin loader. Registers all Service tools."""
    context.register_tool(name="service_list_services", handler=_service_list_services_handler, schema=SERVICE_LIST_SERVICES_SCHEMA)
    context.register_tool(name="service_get_service", handler=_service_get_service_handler, schema=SERVICE_GET_SERVICE_SCHEMA)
    log.info("Service plugin loaded: 3 tool(s) registered")
