"""
ServiceNow plugin for Hermes Agent — generated by Hermes Developer Agent.
Registers tools: servicenow_list_incidents, servicenow_get_incident, servicenow_create_incident
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys

log = logging.getLogger(__name__)


# ── Tool schemas ──────────────────────────────────────────────────────────────

SERVICENOW_LIST_INCIDENTS_SCHEMA = {
    "type": "object",
    "properties": {},
    "required": [],
    "description": "List all incidents from ServiceNow. Returns a list of records.",
}

SERVICENOW_GET_INCIDENT_SCHEMA = {
    "type": "object",
    "properties": {
        "record_id": {"type": "string", "description": "The ID of the incident to retrieve."},
    },
    "required": ["record_id"],
    "description": "Get a single ServiceNow incident by its ID.",
}

SERVICENOW_CREATE_INCIDENT_SCHEMA = {
    "type": "object",
    "properties": {
        "payload": {"type": "object", "description": "Fields for the new incident."},
    },
    "required": ["payload"],
    "description": "Create a new incident in ServiceNow.",
}

# ── Async → sync bridge (copy verbatim from any existing plugin) ──────────────

def _run(coro):
    """Run an async coroutine from a synchronous tool handler."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(asyncio.run, coro)
                return future.result()
        return loop.run_until_complete(coro)
    except RuntimeError:
        return asyncio.run(coro)


# ── Tool handlers ─────────────────────────────────────────────────────────────

def _servicenow_list_incidents_handler(params: dict, **kwargs) -> str:
    try:
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        from agents.servicenow_agent import list_incidents
        records = _run(list_incidents())
        log.info("servicenow_list_incidents: returned %d records", len(records))
        return json.dumps({"records": records, "count": len(records)})
    except Exception as e:
        log.error("servicenow_list_incidents error: %s", e)
        return json.dumps({"error": str(e)})

def _servicenow_get_incident_handler(params: dict, **kwargs) -> str:
    try:
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        from agents.servicenow_agent import get_incident
        record_id = params.get("record_id", "").strip()
        if not record_id:
            return json.dumps({"error": "record_id is required"})
        record = _run(get_incident(record_id))
        if record is None:
            return json.dumps({"error": f"incident {record_id} not found"})
        return json.dumps(record)
    except Exception as e:
        log.error("servicenow_get_incident error: %s", e)
        return json.dumps({"error": str(e)})

def _servicenow_create_incident_handler(params: dict, **kwargs) -> str:
    try:
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        from agents.servicenow_agent import create_incident
        payload = params.get("payload", {})
        result = _run(create_incident(payload))
        return json.dumps(result)
    except Exception as e:
        log.error("servicenow_create_incident error: %s", e)
        return json.dumps({"error": str(e)})

# ── Plugin entry point ────────────────────────────────────────────────────────

def setup(context) -> None:
    """Called by Hermes Agent plugin loader. Registers all ServiceNow tools."""
    context.register_tool(name="servicenow_list_incidents", handler=_servicenow_list_incidents_handler, schema=SERVICENOW_LIST_INCIDENTS_SCHEMA)
    context.register_tool(name="servicenow_get_incident", handler=_servicenow_get_incident_handler, schema=SERVICENOW_GET_INCIDENT_SCHEMA)
    context.register_tool(name="servicenow_create_incident", handler=_servicenow_create_incident_handler, schema=SERVICENOW_CREATE_INCIDENT_SCHEMA)
    log.info("ServiceNow plugin loaded: 4 tool(s) registered")
