"""
Service Agent — generated by Hermes Developer Agent.
Connects to Service REST API.
Config is read at call time so dotenv always wins.
"""
from __future__ import annotations

import asyncio
import logging
import os
import requests

log = logging.getLogger(__name__)


# ── Config ────────────────────────────────────────────────────────────────────

def _cfg() -> dict:
    """Read config from env at call time — never cached at module load."""
    return {
        "api_base_url": os.environ.get("SERVICE_BASE_URL", "1. *API Base URL* — e.g., <https://your-company.service-now.com|your-company.service-now.com>"),
        "token": os.environ.get("SERVICE_TOKEN", ""),
    }


def _headers(cfg: dict) -> dict:
    return {{
            "Authorization": f"Bearer {{cfg['token']}}",
            "Content-Type": "application/json",
        }}


# ── Sync HTTP calls ───────────────────────────────────────────────────────────

def _sync_list_services() -> list[dict]:
    cfg = _cfg()
    r = requests.get(
        f"{cfg['api_base_url']}/api/service/list",
        headers=_headers(cfg),
        timeout=15,
    )
    r.raise_for_status()
    data = r.json()
    return data if isinstance(data, list) else data.get("result", data.get("items", []))

def _sync_get_service(record_id: str) -> dict | None:
    cfg = _cfg()
    r = requests.get(
        f"{cfg['api_base_url']}/api/service/{record_id}",
        headers=_headers(cfg),
        timeout=15,
    )
    if r.status_code == 404:
        return None
    r.raise_for_status()
    data = r.json()
    return data.get("result", data)

def _sync_update_service(record_id: str, payload: dict) -> dict:
    cfg = _cfg()
    r = requests.patch(
        f"{cfg['api_base_url']}/api/service/{record_id}",
        headers=_headers(cfg),
        json=payload,
        timeout=15,
    )
    r.raise_for_status()
    return r.json().get("result", r.json())


# ── Async wrappers ────────────────────────────────────────────────────────────

async def list_services() -> list[dict]:
    """List all services from service."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_list_services)

async def get_service(record_id: str) -> dict | None:
    """Get a single service by ID."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_get_service, record_id)

async def update_service(record_id: str, payload: dict) -> dict:
    """Update an existing service."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_update_service, record_id, payload)

