"""
ServiceNow Agent — generated by Hermes Developer Agent.
Connects to ServiceNow REST API.
Config is read at call time so dotenv always wins.
"""
from __future__ import annotations

import asyncio
import logging
import os
import requests

log = logging.getLogger(__name__)


# ── Config ────────────────────────────────────────────────────────────────────

def _cfg() -> dict:
    """Read config from env at call time — never cached at module load."""
    return {
        "api_base_url": os.environ.get("SERVICENOW_BASE_URL", "https://instancesigmoid.service-now.com/api/now/table"),
        "username": os.environ.get("SERVICENOW_USERNAME", ""),
            "password": os.environ.get("SERVICENOW_PASSWORD", ""),
    }


def _headers(cfg: dict) -> dict:
    from base64 import b64encode
        creds = b64encode(f"{{cfg['username']}}:{{cfg['password']}}".encode()).decode()
        return {{
            "Authorization": f"Basic {{creds}}",
            "Content-Type": "application/json",
        }}


# ── Sync HTTP calls ───────────────────────────────────────────────────────────

def _sync_list_incidents() -> list[dict]:
    cfg = _cfg()
    r = requests.get(
        f"{cfg['api_base_url']}/incident?sysparm_limit=50&sysparm_display_value=true",
        headers=_headers(cfg),
        timeout=15,
    )
    r.raise_for_status()
    data = r.json()
    return data.get("result", data if isinstance(data, list) else [])

def _sync_get_incident(record_id: str) -> dict | None:
    cfg = _cfg()
    r = requests.get(
        f"{cfg['api_base_url']}/incident/{record_id}",
        headers=_headers(cfg),
        timeout=15,
    )
    if r.status_code == 404:
        return None
    r.raise_for_status()
    data = r.json()
    return data.get("result", data)

def _sync_create_incident(payload: dict) -> dict:
    cfg = _cfg()
    r = requests.post(
        f"{cfg['api_base_url']}/incident",
        headers=_headers(cfg),
        json=payload,
        timeout=15,
    )
    r.raise_for_status()
    data = r.json()
    return data.get("result", data)

def _sync_update_incident(record_id: str, payload: dict) -> dict:
    cfg = _cfg()
    r = requests.patch(
        f"{cfg['api_base_url']}/incident/{record_id}",
        headers=_headers(cfg),
        json=payload,
        timeout=15,
    )
    r.raise_for_status()
    data = r.json()
    return data.get("result", data)


# ── Async wrappers ────────────────────────────────────────────────────────────

async def list_incidents() -> list[dict]:
    """List all incidents from servicenow."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_list_incidents)

async def get_incident(record_id: str) -> dict | None:
    """Get a single incident by ID."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_get_incident, record_id)

async def create_incident(payload: dict) -> dict:
    """Create a new incident."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_create_incident, payload)

async def update_incident(record_id: str, payload: dict) -> dict:
    """Update an existing incident."""
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_update_incident, record_id, payload)

